[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github//MissingSemesterCUET/ML/blob/main/lectures/02.01/notebook2.ipynb)

# Class 2 : Numpy Basics II

In [1]:
import numpy as np

# Matrix Indexing

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

Bad practice:

In [3]:
A[1][2]

np.int64(6)

Best practice: faster, cleaner, mathsy

In [4]:
A[1,2]

np.int64(6)

Wild card

In [5]:
A[1, :]

array([4, 5, 6])

## Transpose

In [6]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Orignal array stays the same

In [8]:
A

array([[1, 2, 3],
       [4, 5, 6]])

## Useful Properties
- $(A^T)^T = A$
- $(AB)^T = B^TA^T$

Don't memorize the second one yet. You'll naturally use it later.

# Reshaping

In [9]:
A.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

Original array stays in the same shape

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6]])

Chaning elements in the reshaped matrix, is reflected in the original matrix

In [11]:
B = A.reshape(6, 1)
B[0,0] = 100
B

array([[100],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6]])

In [12]:
A

array([[100,   2,   3],
       [  4,   5,   6]])

Totla number of elements should remain equal

In [13]:
# A.reshape(2, 2) # Error

A neat trick

In [14]:
A.reshape(3, -1) # -1 is a wild card

array([[100,   2],
       [  3,   4],
       [  5,   6]])

# Row vs Column Vectors

In [15]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [16]:
a.shape

(4,)

This is not a row vector.

It is not a column vector.

It is just a 1D array.

If you want a column vector:

In [17]:
a = a.reshape(-1, 1)
a

array([[1],
       [2],
       [3],
       [4]])

In [18]:
a.shape

(4, 1)

If you want a row vector

In [19]:
a = a.reshape(1, -1)
a

array([[1, 2, 3, 4]])

In [20]:
a.shape

(1, 4)

This distinction becomes important for matrix multiplication.

# Vectors are 1D Matrices (our convention)

Mathematically, vectors are different objects.

But for deep learning, it's convenient to think of them as matrices with one row or one column.

Then the dot product is just matrix multiplication.

In [21]:
a = np.array([1,2,3]).reshape(-1, 3)
a

array([[1, 2, 3]])

In [22]:
b = np.array([4,5,6]).reshape(3,-1)
b

array([[4],
       [5],
       [6]])

In [23]:
dot_product =a @ b
dot_product

array([[32]])

In [24]:
dot_product.item()

32

# Broadcasting

## Matrix + Scalar

In [41]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
A + 10

array([[11, 12, 13],
       [14, 15, 16]])

## Matrix + Row Vector

In [42]:
v_row = np.array([[10, 20, 30]])
A + v_row

array([[11, 22, 33],
       [14, 25, 36]])

## Matrix + Column Vector

In [43]:
v_col = np.array([
    [10],
    [20]
])
A + v_col

array([[11, 12, 13],
       [24, 25, 26]])

## Row Vector + Column Vector

In [44]:
r = np.array([[1, 2, 3]])
c = np.array([
    [10],
    [20],
    [30]
])
r + c

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

## Broadcasting Rules

NumPy compares shapes element-wise starting with the rightmost dimensions and works its way left. Two dimensions are compatible when:
1. They are **equal**.
2. One of them is **1**.

If these conditions are not met, a `ValueError` is raised.

In [ ]:
# A + np.array([[10, 20], [30, 40]]) # Error: operands could not be broadcast together

# Common constructors
- eye
- arange
- linspace
- ones
- zeros

# Norm