<a href="https://colab.research.google.com/github/MissingSemesterCUET/ML/blob/main/lecture1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
1 + 2

3

In [2]:
5 ** 2

25

In [3]:
x = 1

In [4]:
print(x)

1


In [5]:
if x == 1:
  print("X is one")
elif x == 2:
  print("X is two")
else:
  print("X is not one or two")

X is one


In [6]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
a = [2104121, 2104122, 2104123]
print(a)

[2104121, 2104122, 2104123]


In [8]:
len(a)

3

In [9]:
a[2]

2104123

In [10]:
a.append(2104086)
print(a)

[2104121, 2104122, 2104123, 2104086]


In [11]:
b = [1, 1.2, 'CUET', 5]
print(b)

[1, 1.2, 'CUET', 5]


In [12]:
len(b)

4

In [13]:
b[2]

'CUET'

In [14]:
a + b

[2104121, 2104122, 2104123, 2104086, 1, 1.2, 'CUET', 5]

In [15]:
a * 5

[2104121,
 2104122,
 2104123,
 2104086,
 2104121,
 2104122,
 2104123,
 2104086,
 2104121,
 2104122,
 2104123,
 2104086,
 2104121,
 2104122,
 2104123,
 2104086,
 2104121,
 2104122,
 2104123,
 2104086]

In [16]:
ids = {
  'Mahi': 2104121,
  'Zarif': 2104122,
  'Saimun': 2104123
}

In [17]:
ids['Zarif']

2104122

In [18]:
len(ids)

3

In [19]:
squares = []

for i in range(10):
  squares.append(i**2)

print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [20]:
squares = [i**2 for i in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [21]:
def matrix_multiplication(a, b):
  row_a = len(a)
  col_a = len(a[0])
  row_b = len(b)
  col_b = len(b[0])

  if (col_a != row_b):
    return "Error: Number of columns of the multiplicand should be the same as the number of rows of the multiplier"

  result = [[0] * col_b for i in range(row_a)]

  for i in range(row_a):
    for j in range(col_b):
      sum = 0
      for k in range(col_a):
        sum += a[i][k] * b[k][j]
      result[i][j] = sum
  return result

a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
b = [
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
]

matrix_multiplication(a, b)

[[84, 90, 96], [201, 216, 231], [318, 342, 366]]

In [23]:
import torch

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

a + b

tensor([5, 7, 9])

In [24]:
a - b

tensor([-3, -3, -3])

In [25]:
a * b

tensor([ 4, 10, 18])

In [26]:
a.dot(b)

tensor(32)

In [27]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

B = torch.tensor([
    [7, 8],
    [9, 10],
    [11, 12]
])

A.mm(B)

tensor([[ 58,  64],
        [139, 154]])

In [28]:
A @ B

tensor([[ 58,  64],
        [139, 154]])

In [30]:
A.mT

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [31]:
A.shape

torch.Size([2, 3])

In [32]:
A.reshape(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [35]:
A.reshape(-1, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [37]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [43]:
torch.linspace(0, 10, 21)

tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000])

In [44]:
x = torch.arange(0, 10, 2)
x ** 2

tensor([ 0,  4, 16, 36, 64])

In [ ]:
import matplotlib.pyplot as plt

plt