In [1]:
import numpy as np

In [60]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

# a+b
a.__add__(b)

array([11, 22, 33, 44])

In [82]:
class ndarray:
    def __init__(self, data):
        self.data = data
        self.shape = (len(data),)
    
    def __repr__(self):
        return f"array({self.data})"

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value
    
    def __add__(self, other):
        result = []
        for i,j in zip(self.data, other.data):
            result.append(i+j)
        return ndarray(result)
    
    

def array(data):
    return ndarray(data)

a = array([1,2,3,4])
b = array([10,20,30,40])

a*b

TypeError: unsupported operand type(s) for *: 'ndarray' and 'ndarray'

In [72]:
a = [3,4,5]
b = [1,2,3]

result = []
for i,j in zip(a,b):
    result.append(i+j)
print(result)

# [4,6,8]

[4, 6, 8]


In [83]:
class ndarray:
    def __init__(self, data):
        self.data = data
        self.shape = (len(data),)
    
    def __repr__(self):
        return f"array({self.data})"

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value
    
    def __add__(self, other):
        result = []
        for i,j in zip(self.data, other.data):
            result.append(i+j)
        return ndarray(result)
    def __mul__(self, other):
        result = []
        for i,j in zip(self.data, other.data):
            result.append(i*j)
        return ndarray(result)

def array(data):
    return ndarray(data)

a = array([1,2,3,4])
b = array([10,20,30,40])

a*b

array([10, 40, 90, 160])

In [84]:
class ndarray:
    def __init__(self, data):
        self.data = data
        self.shape = (len(data),)

    def __repr__(self):
        return f"array({self.data})"

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value

    def __add__(self, other):
        result = []
        for i, j in zip(self.data, other.data):
            result.append(i + j)
        return ndarray(result)

    def __mul__(self, other):
        result = []
        for i, j in zip(self.data, other.data):
            result.append(i * j)
        return ndarray(result)

def array(data):
    return ndarray(data)

a = array([1,2,3,4])
b = array([10,20,30,40])

print(a * b)

array([10, 40, 90, 160])
