# Class 3: NumPy from Scratch

We won’t try to recreate all of NumPy (that would take years). Instead, we’ll build a mini-NumPy that teaches the core concepts.

# Intro to OOP

I know many of you are not familiar with OOP. So, we will teach you the basics of OOP along the way.

The concept of OOP was created to make the lives of programmers easier. Theoretically, we can build build anything from scratch without ever knowing what OOP is. But that will be very very very difficult. With OOP, its much easier.

Altough it came to make our lives, easier, it's not taugh very well. So, students are often afraid of OOP.

Here is big idea of OOP:

When you start a new project, with a blank screen infront of you, with no code written yet, don't just start writing the code. Think about what are the **objects** you are going to work with.

Say you want to build a classroom management system for CUET.

The object for you are:
- students
- teachers
- courses
- classroom

After you have created the list of objects, think about what properties/attributes do the objects have.

For example:
- Attrs of student:
    - name
    - student id
    - student email
    - dept
    - batch
    - hall name
- Attrs of teacher:
    - name
    - teacher id
    - teacher email
    - dept
    - affiliation
- Attrs of course:
    - name
    - course id
    - list of course teachers
- Attrs of classroom
    - room number
    - building number
    - lab/class

Then think about how each of the objects **behave** (what they can do. we call them methods).

Example:
- Methods of student:
    - can enroll in course
    - can attend a class
- Methods of teacher:
    - can conduct a course
    - can take attendance
- Methods of course:
    - cant do anything
- Methods of classroom:
    - cant do anything

That's all OOP is

# Exercise: Create a representation of Cat

Attributes:
- name
- breed

Methods:
- meows

In [6]:
class Cat:
    name : str
    breed : str

c = Cat()
c.name = "Leo"
c.breed = "Persian"

c.name

'Leo'

Now the methods

In [10]:
class Cat:
    name : str
    breed : str

    def meow(self):
        print(f"{self.name} says Meow")

c = Cat()
c.name = "Sultan"
c.meow()

Sultan says Meow


A syntactice sugar to make it look more elegant:

In [ ]:
class Cat:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def meow(self):
        print(f"{self.name} says Meow")

c = Cat(name="KD", breed="Deshi")
c.meow()

KD says Meow


# v1: As simple as possible

Let's create the simplest version of numpy. We will make it as simple as possible.

We will replicate these behaviors:

In [18]:
import numpy as np

a = np.array([1,2,3])
type(a)

numpy.ndarray

In [22]:
a

array([1, 2, 3])

Yes, that's all we want for v1.

But before that, recall the big idea of OOP. To make our lives easier, we should just start writing code. We should first think about what are the objects we are going to work with.

In this simple version of numpy, there will only be one object - `ndarray` (We could also call it a tensor, but let's stick to the conventions of numpy)

What attributes should it have? For now, it should just be able to hold a list of numbers. That's all.

In [3]:
class ndarray:
    def __init__(self, data):
        self.data = data
    
def array(data):
    return ndarray(data)

a = array([1,2,3])
type(a)

__main__.ndarray

Let's print `a`

In [4]:
a

That doesn't look great. This is python's default way of representing types. We can override it with the `__repr__` method

In [ ]:
class ndarray:
    def __init__(self, data):
        self.data = data

    def __repr__(self):
        return f"array({self.data})"
    
def array(data):
    return ndarray(data)

a = array([1,2,3])
a

array([1, 2, 3])

# v2: More dunder methods

In [ ]:
class ndarray:
    def __init__(self, data):
        self.data = data
        self.shape = (len(data),)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value

    def __repr__(self):
        return f"array({self.data})"


def array(data):
    return ndarray(data)

Let's test it out

In [32]:
a = array([1,2,3,4])
print(a)
print(len(a))
print(a[0])

a[0] = 10
print(a)

array([1, 2, 3, 4])
4
1
array([10, 2, 3, 4])


# v3: Element-wise Operations

The important thing to realize is that when we write
```py
c = a + b
```

Python actually calls
```py
c = a.__add__(b)
```

Similarly,
```py
a - b   --> a.__sub__(b)
a * b   --> a.__mul__(b)
a / b   --> a.__truediv__(b)
```

So we'll implement those methods directly.

In [34]:
class ndarray:
    def __init__(self, data):
        self.data = data
        self.shape = (len(data),)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value

    def __repr__(self):
        return f"array({self.data})"

    def __add__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a + b)

        else:  # scalar
            for a in self.data:
                result.append(a + other)

        return ndarray(result)

    def __sub__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a - b)

        else:
            for a in self.data:
                result.append(a - other)

        return ndarray(result)

    def __mul__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a * b)

        else:
            for a in self.data:
                result.append(a * other)

        return ndarray(result)

    def __truediv__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a / b)

        else:
            for a in self.data:
                result.append(a / other)

        return ndarray(result)


def array(data):
    return ndarray(data)

In [35]:
a = array([1, 2, 3])
b = array([4, 5, 6])

print(a + b)
# array([5, 7, 9])

print(a - b)
# array([-3, -3, -3])

print(a * b)
# array([4, 10, 18])

print(b / a)
# array([4.0, 2.5, 2.0])

print(a + 10)
# array([11, 12, 13])

print(a * 5)
# array([5, 10, 15])

array([5, 7, 9])
array([-3, -3, -3])
array([4, 10, 18])
array([4.0, 2.5, 2.0])
array([11, 12, 13])
array([5, 10, 15])


**A small observation**

You probably noticed that __add__, __sub__, __mul__, and __truediv__ are almost identical. Real libraries avoid this repetition by having all four call a common internal helper. For learning purposes, though, writing them out separately makes it much easier to see exactly what each operator is doing before we start refactoring.

# v4: Reduction Methods (Exercise)

In [37]:
a = np.array([1, 2, 3, 4])

print(a.sum())     # 10
print(a.mean())    # 2.5
print(a.min())     # 1
print(a.max())     # 4

10
2.5
1
4


Home work:
- `prod()`
- `std()`
- `var()`
- `argmin()`
- `argmax()`

**What you just learned**

Until now, every operation returned another array.

a + b --> array([...])

A reduction is different.

array([5, 1, 8, 2]) --->reduce(sum)---> 16

Instead of producing another array, it produces a single number.