[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github//MissingSemesterCUET/ML/blob/main/lectures/02.02/notebook2.ipynb)

# Class 3: NumPy from Scratch (Part II)

In [2]:
import numpy as np

In [5]:
class ndarray:
    def __init__(self, data):
        self.data = data
        self.shape = (len(data),)
    
    def __repr__(self):
        return f"array({self.data})"

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value
    

def array(data):
    return ndarray(data)

# v3: Element-wise Operations

The important thing to realize is that when we write
```py
c = a + b
```

Python actually calls
```py
c = a.__add__(b)
```

Similarly,
```py
a - b   --> a.__sub__(b)
a * b   --> a.__mul__(b)
a / b   --> a.__truediv__(b)
```

So we'll implement those methods directly.

In [6]:
class ndarray(ndarray):
    def __add__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a + b)

        else:  # scalar
            for a in self.data:
                result.append(a + other)

        return ndarray(result)

    def __sub__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a - b)

        else:
            for a in self.data:
                result.append(a - other)

        return ndarray(result)

    def __mul__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a * b)

        else:
            for a in self.data:
                result.append(a * other)

        return ndarray(result)

    def __truediv__(self, other):
        result = []

        if isinstance(other, ndarray):
            if self.shape != other.shape:
                raise ValueError("Shapes must match.")

            for a, b in zip(self.data, other.data):
                result.append(a / b)

        else:
            for a in self.data:
                result.append(a / other)

        return ndarray(result)


def array(data):
    return ndarray(data)

In [7]:
a = array([1, 2, 3])
b = array([4, 5, 6])

print(a + b)
# array([5, 7, 9])

print(a - b)
# array([-3, -3, -3])

print(a * b)
# array([4, 10, 18])

print(b / a)
# array([4.0, 2.5, 2.0])

print(a + 10)
# array([11, 12, 13])

print(a * 5)
# array([5, 10, 15])

array([5, 7, 9])
array([-3, -3, -3])
array([4, 10, 18])
array([4.0, 2.5, 2.0])
array([11, 12, 13])
array([5, 10, 15])


**A small observation**

You probably noticed that __add__, __sub__, __mul__, and __truediv__ are almost identical. Real libraries avoid this repetition by having all four call a common internal helper. For learning purposes, though, writing them out separately makes it much easier to see exactly what each operator is doing before we start refactoring.

# v4: Reduction Methods (Exercise)

In [8]:
a = np.array([1, 2, 3, 4])

print(a.sum())     # 10
print(a.mean())    # 2.5
print(a.min())     # 1
print(a.max())     # 4

10
2.5
1
4


Home work:
- `prod()`
- `std()`
- `var()`
- `argmin()`
- `argmax()`

**What you just learned**

Until now, every operation returned another array.

a + b --> array([...])

A reduction is different.

array([5, 1, 8, 2]) --->reduce(sum)---> 16

Instead of producing another array, it produces a single number.

In [ ]:
a = np.array([1,2,3])
help(a.argmin)
help(a.argmax)

Help on built-in function argmin:

argmin(axis=None, out=None, *, keepdims=False) method of numpy.ndarray instance
    a.argmin(axis=None, out=None, *, keepdims=False)

    Return indices of the minimum values along the given axis.

    Refer to `numpy.argmin` for detailed documentation.

    See Also
    --------
    numpy.argmin : equivalent function

Help on built-in function argmax:

argmax(axis=None, out=None, *, keepdims=False) method of numpy.ndarray instance
    a.argmax(axis=None, out=None, *, keepdims=False)

    Return indices of the maximum values along the given axis.

    Refer to `numpy.argmax` for full documentation.

    See Also
    --------
    numpy.argmax : equivalent function

